### ISSUE TITLE
Problem with storybook build failing depending on the state of package lock

### ISSUE THREAD

**Issue by ktw1016** [TBS-EACPD/infobase#1092]
For whatever reason, if you do a clean install: `remove node_modules and pacakge-lock.json` -> `npm install`
Storybook is failing on the resulting lock file.

Error msg is something like: `TypeError: Cannot read property 'get' of undefined`

As a workaround, we're not doing a clean install, and only doing `npm install <dependency>` on top of the existing `package-lock.json` on master. However, this is only short-term temporary solution and it's something that should be taken care of sooner or later

Things I've tried fixing:
- Installing `dotenv-webpack`: It fixed for me locally but fails on CI with the message `The 'compilation' argument must be an instance of Compilation`
- Updating storybook to 6.2.5 and/or 6.2.9: Still fail
- I also tried all the combinations above (6.2.5 and 6.2.9 with/without dotenv-webpack)
- Tried setting `config.resolve.fallback = { http: false, }`

Links for fixing I looked into:
https://github.com/storybookjs/storybook/issues/14497
https://stackoverflow.com/questions/67070802/webpack-5-and-storybook-6-integration-throws-an-error-in-defineplugin-js

**Comment by ktw1016** [comment]
I think that new "compilation error" might be fixed with this? https://github.com/jantimon/html-webpack-plugin/issues/1451#issuecomment-712581727 didn't bother to try because I worried it'd be going to too hacky territory

**Comment by Stephen-ONeil** [comment]
> * Installing `dotenv-webpack`: It fixed for me locally but fails on CI with the message `The 'compilation' argument must be an instance of Compilation`

I get `The 'compilation' argument must be an instance of Compilation`'s locally in that instance too. Might be a linux thing, will look in to it more some time myself.

It won't close this issue, but it would be more secure if we could identify what versions of what packages cause this and lock them down (temporarily) in our `package.json`. It's not just a clean install that could cause this, an upgrade or even an audit (if one of the "good" versions requires an update to address a security concern) could also bump whatever the working combination of packages is up to whatever the broken combination of packages is.

I hadn't bothered locking any versions because I was kinda hoping things were getting fixed upstream. Some of those issues you linked with workarounds for these errors are over half a year old and already closed though. We might need to go the length of documenting/recreating this and opening a new issue about it if we actually want it fixed.

**Comment by ktw1016** [comment]
Good point, locking down the "good" version of problematic packages would justify to remove the urgent tag

**Comment by Stephen-ONeil** [comment]
Update: everything is working for me with storybook `6.3.0-rc.5`

Someone reopened the closed .env issue [here](https://github.com/storybookjs/storybook/issues/14403), fix got in to the release candidate [here](https://github.com/VandyHacks/vaken/pull/821). Presumably our secondary issues were resolved somewhere else. 

I'll be watching for the official 6.3.0 release. Expect a little bit of migration issues in the switch (getting some webpack config warnings on the release candidate), but should finally be able to move past this :+1:

**Comment by Stephen-ONeil** [comment]
Not immediately clear if this (or the .env related portion at least) was actually intentionally fixed. Not seeing any specific storybook PRs or commits in `6.4.0-rc.5` referencing the current issue. Possible it was indirectly fixed in the process of other storybook dependency changes :shrug:. Fingers crossed 6.3.0 still resolves it all once it drops.

**Comment by Stephen-ONeil** [comment]
Oops, closed by #1165
