### ISSUE TITLE
Dropdown filter for display table

### ISSUE THREAD

**Issue by ktw1016** [TBS-EACPD/infobase#1223]
<img width="165" alt="Screen Shot 2021-08-13 at 12 31 00 PM" src="https://user-images.githubusercontent.com/29746626/129390771-53d944ef-f48a-4dd9-a0b7-8fc68183f8b6.png">

<img width="72" alt="Screen Shot 2021-08-13 at 12 29 12 PM" src="https://user-images.githubusercontent.com/29746626/129390666-d63aa8c2-43ec-4311-ab61-b88b5a31349f.png">

So I'm imagining when you click the arrow on the first pic, dropdown (like 2nd pic) would come down for filtering
This would be pretty cool

**Comment by Stephen-ONeil** [comment]
So a combination input search and checklist filter? Could be useful on some columns, although some (like the first index on most tables) could be unique per-row so the checklist would be similar length to the table.

If we do something like this, we should try to match the UI/behaviour of something like excel or google sheets, so that we can lean on what users are familiar with (otherwise, it seems like something that'd be tricky to figure out).

**Comment by ktw1016** [comment]
Yeah agreed this will and should only be applied carefully on columns where values are limited so that the dropdown list of values are controlled. And agreed on the behaviour of excel, in fact, image I got of the dropdown list is screenshot of excel!
