### ISSUE TITLE
Cookie issue

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#266]
Getting a bunch of warnings with the following:

> A cookie associated with a cross-site resource at http://canada.ca/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by Stephen-ONeil** [comment]
Doubleclick is Google Analytics.

We're using a pretty out of date Google Analytics API I think, so probably updating that would resolve this as I don't think Google would be gearing up to block their own analytics platform (at least not by default). I don't remember if the reason we haven't updated it is because its in the index html files or because there was some complication from us not being recognized as the domain owner for tbs-sct.gc.ca.

**Comment by Stephen-ONeil** [comment]
As per #296 

> Upon further investigation, the warnings discussed in #266 are out of our control (unless we want to get real hacky). Those cookies are created on a Google server and sent down to the client, and the API **doesn't** let us tell the backend what we want in the relevant fields. The fix will come in its own time when Google updates their service.
