### ISSUE TITLE
copy google's accessibility strategy

### ISSUE THREAD

**Issue by AlexCLeduc** [TBS-EACPD/infobase#28]
Just accidentally tabbed onto some hidden a11y google links and was really impressed, we can probably steal a few ideas from google.

the first three things you can focus on are, in order:
1. skip to main content : goes to first search result
2. [accessibility help](https://support.google.com/websearch/answer/181196?hl=en-CA)
3. [accessibility feedback](

I think we should have these three links on both apps, in every single route.

* The behaviour of the first link would change based on sub-app (the sub-app would now be required to identify their "first focusable main content element", is that a solved problem already ? )
* accessibility help can be its own sub-app, but the safer thing to do would be to make it its own page separate from the other 2 sub-apps. It would probably be fine for this page to be visited via `storage.google/<bucket-url>` or whatever.
* accessibility feedback can be a new survey that comms builds for us. Or some kind of custom solution...

**Comment by GarvinH** [comment]
I think we'd have to restructure our HTML before we start this.

Right now the a11y link header is hard to add any sort of dynamic content into (since it's baked into the HTML file) which makes it hard to have the skip to main content feature.

Accessibility feedback would ideally show as a pop up like how google does it, but that also mean's we'd have to handle this with react as well. Otherwise we can do it as an external link (but then focus would start at the top again and so the user would go through the "accessibility feedback" link again when tabbing through, which might be confusing?

**Comment by Stephen-ONeil** [comment]
Easy to add React to static HTML, see [portals](https://reactjs.org/docs/portals.html). We use them a couple of times in `NavComponents.js` for example; this would be a lot like how the nav breadcrumbs already work. 

One small headache is that the existing text-only version link is only in the non-a11y index html files, but not a show stopper.
