### ISSUE TITLE
moving css rules out of extended-bootstrap.css

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#41]
Since these have to be cache busted manually after deployment it makes changing the panel CSS a riskier proposition than it should be. But, there's lots of stuff in this particular file that doesn't need to be loaded from index.html (all the panel CSS for example). We should keep the extended-bootstrap.css file as minimal as possible.

This could be combined with #682 (and a more general CSS cleanup)

**Comment by cookkate** [comment]
To be done along with #84

**Comment by ktw1016** [comment]
Should this be closed, as #916 exists?

**Comment by Stephen-ONeil** [comment]
No, this is a totally different thing.

**Comment by Stephen-ONeil** [comment]
For context, `extended_bootstrap_css` is a set of styles that get bundled in together with bootstrap by the `IB_base` command. The output css file is required directly by the index html files, rather than being a part of the webpack bundles. In part this is for the styles necessary to properly render the header/footer in the index files (to reduce the amount of re-styles as the later webpack css loads in), but it's also where a bunch of legacy holdovers and bootstrap over rides live. Just like `common_css`, it's a poorly organized mess full of legacy styles that may or may not be used anywhere any more.

... but now that I look at it, this specific issue doesn't make too much sense (the claims about risk aren't founded), and may have already been addressed (it specifically mentions panel css, which already moved out).

A general cleanup of all the legacy and centralized css in `extended_bootstrap_css` and `common_css` deserves it's own issue, but this one can close.
