### ISSUE TITLE
Google search snippets for GC infobase include "please enable javascript" error page

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#470]
Weirdly only for the tag explorer snippet (none of the others).

Might not be much we can do.

![Screen Shot 2020-01-23 at 2 33 51 PM](https://user-images.githubusercontent.com/10406459/73017283-866c2800-3ded-11ea-95e1-4e4052603796.png)

**Comment by Stephen-ONeil** [comment]
Did some googling on this, looks like maybe Google always indexes the content of a noscript tag, [at least in 2010](https://webmasters.stackexchange.com/a/1688). I doubt they've changed their underlying reasoning/methodology since then, even if websites that don't work without JS are far more common now.

Could be something else about the particular page(s) this happens for (I'm seeing it for rpb in current searches). Appears to have proper metadata for title and description though. Can't think of any other obvious reasons google would give so much priority to the noscript.

Note that the noscript content DOES always show up at the top of the body, so if google is crawling it then it's possible that if the meta tags aren't set it **would** have high priority.

**Comment by Stephen-ONeil** [comment]
Suggested fix could be nuking the noscript tag from JS (maybe in app bootstrap or something). That should keep it out of search indexes (unless google really is choosing to crawl and index the site without JS, in which case we're probably out of luck).
