### ISSUE TITLE
Performance implications of using explicit lodash chains over implicit chains

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#522]
The explicit syntax is `_.chain(...)...value()`, implicit is `_(...)...` (note: doesn't `.value()` call). Turns out only the implicit version is [lazy/benefits from "shortcut fusion"](orgs/tag/HI1029/infograph/intro).

We should benchmark some pages, run a code mod to switch to all implicit calls, and see if there's any significant performance boost! In the future, if we take the time to learn the set of optimizable utilities, we could write (marginally?) more performant lodash chains.

**Comment by Stephen-ONeil** [comment]
Don't expect it to blow your socks off, but it should be a practically free optimization to make.

**Comment by ktw1016** [comment]
Hmm briefly tried it out, it doesn't seem to work the exact same by changing to implicit call? (removing `_.chain` -> `_` and `.value()`)

**Comment by Stephen-ONeil** [comment]
Huh, what seemed to go wrong?

**Comment by ktw1016** [comment]
Either logic not functioning as it used to or site is crashing with not good error message. I didn't look deep into it

**Comment by Stephen-ONeil** [comment]
Off the top of my head, might be because we've added one or two extensions to lodash in `client/src/app_bootstrap/lodash-extensions.side-effects.js`. Might be that they way we extend that, they don't exist when using an implicit chain?

**Comment by ktw1016** [comment]
Hmm.. I don't think that's it but I could be wrong. And I don't know why it doesn't work as I've tried a few more times in different ways..

**Comment by GarvinH** [comment]
Didn't really expect it to have a performance increase!

![image](https://user-images.githubusercontent.com/25855114/115744256-6749a680-a360-11eb-9167-54d3a0552b78.png)

I'd assume the best "code mod" for this type of change would be to use eslint-lodash but unfortunately it's not one of the auto-fixable ones. Probably gonna manually look through all use cases to make sure it's a changeable one. We'd only want to use implicit chaining if the final value is a final value anyways (ie. non-array, non-object)

**Comment by GarvinH** [comment]
we can still go ahead and change the `_.chain().value()` to the global function if we wanted to

![image](https://user-images.githubusercontent.com/25855114/115752863-84827300-a368-11eb-8a87-f769f7d7f258.png)


But I honestly think it would probably be better to use the `chain` function explicitly during explicit chains

**Comment by GarvinH** [comment]
Okay, I have a feeling that this isn't really worth the effort haha

In #1038, I've already moved all the single value end result chains to be implicit, but now that I'm debugging, it throws a bunch of errors everywhere and I am now required to revert it back to explicit chaining. (I feel like by the time i'm done reverting everything, over half of the implicit chains will be back to explicit haha)

![image](https://user-images.githubusercontent.com/25855114/115878520-a3d7d980-a416-11eb-9214-ffbd2910e80f.png)

I think using implicit chaining would be way too inconsistent since it works maybe less than half the time.


IMO, we should probably make this a won't fix issue. Otherwise, the next best thing would be to manually test every single conversion to see if it breaks something or not. I have low faith in our browser tests to make sure #1038 doesn't break anything else.

**Comment by Stephen-ONeil** [comment]
From the [docs](https://lodash.com/docs/3.10.1#lodash)
>The wrapper methods that are not chainable by default are: ... deburr, ...

Pretty long list of methods that will terminate the implicit chain (cause of that error at least, probably most of them if not all), but I think wrapping these in a `thru` where they appear as an intermediate step would preserve the chain. That seem worth investigating?

**Comment by GarvinH** [comment]
Ok I did some investigating

when they say "not chainable", what they mean is that after any of those functions, the chain is killed right then and there

![image](https://user-images.githubusercontent.com/25855114/115890036-83ae1780-a422-11eb-9ef5-a403e9faf366.png)

So basically any function that produces a single value will immediately call `.value()`.

![image](https://user-images.githubusercontent.com/25855114/115890268-c374ff00-a422-11eb-9d4b-06d806f424b4.png)
^ Trying to call `deburr()` on `String` class

We have quite a fair amount of stuff that produce a single value but we don't stop right away once a single value is obtained.

**Comment by GarvinH** [comment]
Ok sorry deleted the old comment since everything finally added up and I was kinda spouting the same stuff again.

I'm assuming you mean like this?

![image](https://user-images.githubusercontent.com/25855114/115892435-236ca500-a425-11eb-828d-5b1ff9bde0fe.png)


In which case, I feel like that would be a little excessive haha

**Comment by GarvinH** [comment]
![image](https://user-images.githubusercontent.com/25855114/115892919-a5f56480-a425-11eb-8e9c-c00fc4764c42.png)

Well it definitely seems like using `.thru()` still is a time saver in most cases haha

**Comment by Stephen-ONeil** [comment]
`thru` unwraps the lodash wrapped value before passing it to the applied function, the point is that the value returned by `thru` will be once again wrapped (so it won't terminate the lodash chain).

I meant something like
```
_("tést").thru(_.deburr).trim()
```

**Comment by GarvinH** [comment]
Closing this because the performance gained vs the trade offs aren't really that great. Maybe we could reconsider this if there's a situation where we find that using implicit chaining provides a significant performance boost. 

1. In general, the amount of time gained by using implicit chaining is between 0-0.02 ms (but also sometimes takes longer than the explicit chaining to run meaning that it's possible there isn't really any performance gain in the larger scope of things). But if we assume that every single implicit chain saved 0.02ms, it would take 50000 of these chain calls to even be saving 1 second! (I HIGHLY doubt that we'd even reach 50000 chains for a while. Right now we have approximately 700 chains across the entire code base for reference. Assuming we'd reach 50000 chains, it would all have to be on the same page for this 1 second gain to even occur!) When profiling on slower devices (the surface tablet for example), it's even harder to gauge whether the implicit chaining is really making a difference because of inconsistencies in network/device loading.

2. If we switched to using implicit chains, we'd probably have to break the consistency of our chaining because implicit chaining automatically stops when there is a `chain-breaking method` which requires us to either: 
  1. Unintuitively use a `.thru` to run these chain breakers, or
  2. Keep using explicit chains (which would mean having a mix of implicit and explicit chains, but that isn't that big of a problem with the help of eslint making sure that the mix consistency is correct)

3. All of these changes will have to be manually done (I mean i've done a fair portion, but it's only for the chains that end with a singular value without a chain breaker in between, so we'd still have to change the ones where there is an explicit chain being used unnecessarily) 



Steps if we want to really implement this later on:

1. Add "lodash/chain-style" to eslint config and set to "as-needed"
2. Turn all unnecessary explicit chains to implicit chains (view errors)
3. remove all `.value()` wraps from the implicit chains that end with a singular value (view errors)
4. That should be it

**Comment by Stephen-ONeil** [comment]
Importantly, you found the available linter rules to not be very helpful, right? So this would primarily fall on developers writing/reviewing lodash-heavy code to enforce. It's also a bunch of additional rules for new developers to learn, on top of the challenge of getting comfortable with lodash in the first place.

**Comment by GarvinH** [comment]
In the end, I found the linter to be helpful in converting from explicit to implicit (but never on using implicit properly but this is only a problem for converting existing chains, but that isn't really a problem if following the above steps) I'm not sure how much that would change our stance on this though. But for sure there is definitely an added learning curve on the idea of chain breaking methods!
