### ISSUE TITLE
Really prominent footnote about Motor Car Allowance

### ISSUE THREAD

**Issue by rossbm** [TBS-EACPD/infobase#536]
In the estimates comparison, there is a very prominent footnote at the department level for several departments that mentions that the Salary and Motor Car Allowance items have been combined. I don't think it needs to be so prominent. Can it be collapsed or or just moved to the actual stat item?

**Comment by NicolasGermain** [comment]
There are also some non-relevant footnotes in the estimates comparison.  Maybe it is using keys it shouldn't?

PSEP has 
"The significant increase in unused authorities in 2014-15 and 2015-16, when compared to 2013-14, is primarily due to deferred requests for payments by provinces from the Disaster Financial Assistance Arrangements (DFAA) contribution program."
and TBs has:
"The variance between the amount TBS has spent with what had been authorized by Parliament is mainly attributable to the way that government-wide funds are transferred between the Secretariat and other government organizations. Every year, the Secretariat includes funding in its reference level to be transferred to other government organizations once specific criteria are met. If these funds are needed, they are transferred to the appropriate department. If they are not needed, the unused balance is returned to the consolidated revenue fund at the end of the fiscal year and is reported as a Secretariat lapse."

**Comment by bill-lliu** [comment]
to have this:
![download](https://user-images.githubusercontent.com/26264647/75491213-985c6000-5983-11ea-908a-d781fb73d6a8.png)

placed here instead:
![download (1)](https://user-images.githubusercontent.com/26264647/75491219-9abeba00-5983-11ea-8460-8ec54f2aaf0d.png)

**Comment by ktw1016** [comment]
@bill-lliu uhhh is this one fixed? haha
