### ISSUE TITLE
storybook-ing panel-subject combination cases (e.g. programs w/ out spending, etc. )  

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#64]
* subject-mocking API ? 
 * tests will help move to graphql
 * doesn't need to use storybook, could simply beef up the panel inventory
 * good for business knowledge and exposes bulk of the InfoBase code

**Comment by Stephen-ONeil** [comment]
Expand list of test subjects on the #panel-inventory route, add more text explaining what makes each case special.

**Comment by Stephen-ONeil** [comment]
We'd dropped storybook for a while, which changed the focus of this PR from storybooks to the `#panel-inventory`. Worth debate/deeper thought on if there's any benefit to deprecate the panel inventory for and make panel storybooks instead.

Note for the future, the special cases should be represented with mocked data, but include references to actual instances of the special case (when possible, but time stamped since underlying data may change the nature of some special cases over time).
