### ISSUE TITLE
"some things to keep in mind" sticky positioning is a little janky

### ISSUE THREAD

**Issue by AlexCLeduc** [TBS-EACPD/infobase#952]
It would be nice if my the panel's Y coordinates didn't shift when the element goes from static to fixed positioning. My guess is that the element being removed from static positioning is shifting the panel upwards. 

If we can't use real sticky positioning, maybe we can leave a copy of the element (or another element with equivalent height)  in static positioning, so nothing else has to move up 

![ib-sticky-header-janky](https://user-images.githubusercontent.com/7769215/111645252-e6364700-87d6-11eb-9948-0760024c4355.gif)

**Comment by GarvinH** [comment]
Stepping away to work on a different PR.

Grabbing height is kinda not what I was expecting... 
It's grabbing the height of the accordion but somehow manages to skip the margin on the bottom?

if the accordion is expanded, the clipping will still be present if using a duplicate child (because the state of the second child will be undefined)
