### ISSUE TITLE
Decimal2 and Dollar not being parsed into numbers

### ISSUE THREAD

**Issue by GarvinH** [TBS-EACPD/infobase#977]
Currently `DisplayTable` is treating decimal2 and dollar as string values (since having 2 decimals requires a string format) causing the text align to stay on the left and total not summing up properly (also causing the table to be gigantic)

Should be done before #456 

Waiting for #921

**Comment by Stephen-ONeil** [comment]
Can you add links to some examples?

**Comment by GarvinH** [comment]
I don't think this is actually present in any of the tables on infobase (that is, I don't think any tables right now use decimal2 or dollar). This issue is mainly a precursor to #456.

But if you change the tables for `programSpending` to use `dollar` and go to spending on RPB

![image](https://user-images.githubusercontent.com/25855114/112880369-5925a480-9098-11eb-9509-e40b2a149478.png)

**Comment by Stephen-ONeil** [comment]
I think that's just a miss-use of the (admittedly pretty bad) `DisplayTable` API? Are the values already formatted as strings before being passed in? They should be passed in as numbers, with the dollar formatter set in the column config.

#456 is only about using the correct formatters for display. The values should just be normal JS numbers in storage/when doing math with them. I believe the point of that issue was to review the formatters being used in general, as FTEs CAN be decimal values but are generally still being formatted as ints for display?

**Comment by GarvinH** [comment]
Yea if I remember correctly, the values were being passed in as strings into `DisplayTable`
